Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,13 +26,15 @@ jobs:
             for patch in "$PATCH_DIR"/*.patch; do
               if [ -f "$patch" ]; then
                 if git apply --check "$patch" > /dev/null 2>&1; then
-                  echo "Patch $(basename "${patch%.*}") has already been applied, skipping"
+                  echo "Patch $(basename "${patch%.*}") was already applied, skipping"
                 else
+                  # Partially applied, or applied at all
                   if git apply --reverse --check "$patch" > /dev/null 2>&1; then
                       git apply --reject --whitespace=fix "$patch" || exit 1
                       echo "Applied patch ${patch##*/}"
                   else
-                      echo "Patch $(basename "${patch%.*}") has already been applied, skipping"
+                    echo "Failed to apply patch $(basename "${patch%.*}"). Check if there is a confict."
+                    exit 1
                   fi
                 fi
               fi
